### ISSUE TITLE
XPlatformMenus sample InvalidOperationException

### ISSUE THREAD

**Issue by vrodax** [MvvmCross/MvvmCross-Samples#55]
I ran the XPlatformMenus sample app on the Android SDK emulator configured for KitKat.  I get an InvalidOperationException when I do th following:
 Click Login
Open Hamburger menu and select Recycler view.
Click back button twice.

An unhandled exception is thrown.

You can also dup this by returning to the home screen and clicking the button on home screen until it attempts to save and close which has the same effect as repeatedly hitting the back button.

The problem appears to be that the home fragment is in two consecutive locations in the FragmentManager's list.  When you hit back the first time you return to the home fragment.  When you hit it again it attempts to add the fragment again which causes the exception to be thrown.

**Comment by Cheesebaron** [comment]
Works fine here. No InvalidOperationException is thrown.

**Comment by vrodax** [comment]
Will get it for you tonight when I get back home.

**Comment by vrodax** [comment]
Sorry, it appears that I left out a step.  Here are the updated duplication steps:

Click Login
Open Hamburger menu and select Recyclerview.
Open Hamburger menu and select Home.  (I left this one out before.)
Click back button twice.

The Exception message is:
Fragment already added: HomeFragment{9609a480 #0 id=0x7f060073 XPlatformMenus.Core.ViewModels.HomeViewModel}

I have attached an image of the callstack and the Android SDK Emulator settings.

![emulatorsettings](https://cloud.githubusercontent.com/assets/20866899/19209426/29274b94-8cd8-11e6-9c68-01ec1c96a819.PNG)
![stacktrace](https://cloud.githubusercontent.com/assets/20866899/19209428/2eef5b16-8cd8-11e6-99dc-9ad5a13d2b09.png)

**Comment by vrodax** [comment]
Sorry.  I didn't mean to close this.  I'm kind of new at GitHub.

**Comment by vrodax** [comment]
Here is a text version of the stack trace from the Output window of the debugger:

10-07 21:53:48.322 I/MonoDroid( 1174): UNHANDLED EXCEPTION:
10-07 21:53:48.372 I/MonoDroid( 1174): Java.Lang.IllegalStateException: Fragment already added: HomeFragment{9609a480 #0 id=0x7f060073 XPlatformMenus.Core.ViewModels.HomeViewModel}
10-07 21:53:48.372 I/MonoDroid( 1174):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/3819/c1d1c79c/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
10-07 21:53:48.372 I/MonoDroid( 1174):   at Java.Interop.JniEnvironment+InstanceMethods.CallBooleanMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00084] in /Users/builder/data/lanes/3819/c1d1c79c/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11304 
10-07 21:53:48.382 I/MonoDroid( 1174):   at Android.Runtime.JNIEnv.CallBooleanMethod (System.IntPtr jobject, System.IntPtr jmethod) [0x00000] in /Users/builder/data/lanes/3819/c1d1c79c/source/monodroid/src/Mono.Android/JNIEnv.g.cs:114 
10-07 21:53:48.382 I/MonoDroid( 1174):   at Android.Support.V4.App.FragmentManagerInvoker.PopBackStackImmediate () [0x00033] in <27c17fe440cf491ba8255bcefade6e02>:0 
10-07 21:53:48.382 I/MonoDroid( 1174):   at MvvmCross.Droid.Support.V7.AppCompat.MvxCachingFragmentCompatActivity.OnBackPressed () [0x00014] in <7a18bda9f60f447ca10da0e8629c4104>:0 
10-07 21:53:48.382 I/MonoDroid( 1174):   at XPlatformMenus.Droid.Activities.MainActivity.OnBackPressed () [0x0002e] in D:\dev\MvvmCross-Samples-master\XPlatformMenus\XPlatformMenus.Droid\Activities\MainActivity.cs:73 
10-07 21:53:48.382 I/MonoDroid( 1174):   at Android.App.Activity.n_OnBackPressed (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/3819/c1d1c79c/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.App.Activity.cs:2238 
10-07 21:53:48.382 I/MonoDroid( 1174):   at (wrapper dynamic-method) System.Object:ac642e51-7c2a-4b4f-ae43-412be857953b (intptr,intptr)
10-07 21:53:48.392 I/MonoDroid( 1174):   --- End of managed Java.Lang.IllegalStateException stack trace ---
10-07 21:53:48.392 I/MonoDroid( 1174): java.lang.IllegalStateException: Fragment already added: HomeFragment{9609a480 #0 id=0x7f060073 XPlatformMenus.Core.ViewModels.HomeViewModel}
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1323)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v4.app.BackStackRecord.popFromBackStack(BackStackRecord.java:933)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v4.app.FragmentManagerImpl.popBackStackState(FragmentManager.java:1670)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:586)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at xplatformmenus.droid.activities.MainActivity.n_onBackPressed(Native Method)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at xplatformmenus.droid.activities.MainActivity.onBackPressed(MainActivity.java:47)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.app.Activity.onKeyUp(Activity.java:2193)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.app.Activity.dispatchKeyEvent(Activity.java:2423)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:524)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1962)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:3845)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3819)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3518)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3575)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3419)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3392)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3442)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3411)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3551)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3711)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2010)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1704)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1695)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:1987)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.os.MessageQueue.nativePollOnce(Native Method)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.os.MessageQueue.next(MessageQueue.java:138)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.os.Looper.loop(Looper.java:123)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at java.lang.reflect.Method.invokeNative(Native Method)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at java.lang.reflect.Method.invoke(Method.java:515)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-07 21:53:48.392 I/MonoDroid( 1174): 	at dalvik.system.NativeStart.main(Native Method)
